version: '3.8'
services:
  easy_automate:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
    depends_on:
      - selenium
  mcp_server:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - selenium
    command: python -m packages.mcp_server.main
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: 2g