@baseURL = http://localhost:5000

POST {{baseURL}}/applications
Content-Type: application/json

{
  "name": "Google"
}

###

PUT {{baseURL}}/pages/1
Content-Type: application/json

{
  "name": "Google Search",
  "url": "https://www.google.com",
  "application_id": 1,
  "can_be_navigated_to": true,
  "identifying_selectors": [ { "alias": "input", "xpath": "//textarea[@maxlength=2048]" } ],
  "interactive_selectors": {}
}

###

POST {{baseURL}}/pages
Content-Type: application/json

{
  "name": "Google Search Result",
  "url": "",
  "application_id": 1,
  "can_be_navigated_to": false,
  "identifying_selectors": { "searchfield": "//div[@id='searchform']" },
  "interactive_selectors": {}
}

###





###

# @name openSession
POST {{baseURL}}/browser/open
Content-Type: application/json

###

# @session_id = {{openSession.response.body.session_id}}

# @name closeSession
POST {{baseURL}}/browser/{{session_id}}/close
Content-Type: application/json

###

# @name navigateToPage
# @session_id = {{openSession.response.body.session_id}}

POST {{baseURL}}/browser/{{session_id}}/navigate
Content-Type: application/json

{
  "page_id": "1"
}

###

@name clickElement
@session_id = {{openSession.response.body.session_id}}

POST {{baseURL}}/browser/{{session_id}}/click
Content-Type: application/json

{
  "page_id": "<PAGE_ID>",
  "selector_alias": "<SELECTOR_ALIAS>"
}

###

# @name setElementValue
POST {{baseURL}}/browser/{{session_id}}/set-value
Content-Type: application/json

{
  "page_id": "<PAGE_ID>",
  "selector_alias": "<SELECTOR_ALIAS>",
  "value": "<VALUE>"
}

###

# @name getElementValue
POST {{baseURL}}/browser/{{session_id}}/get-value

Content-Type: application/json
{
  "page_id": "<PAGE_ID>",
  "selector_alias": "<SELECTOR_ALIAS>"
}

###

# @name waitForPage
POST {{baseURL}}/browser/{{session_id}}/wait-for-page

Content-Type: application/json
{
  "page_id": "<PAGE_ID>",
  "timeout": 10
}

###

# @name getCurrentPage
GET {{baseURL}}/browser/{{session_id}}/get-current-page

###

# @name takeScreenshot
GET {{baseURL}}/browser/{{session_id}}/screenshot
Content-Type: application/json

###

# @name getDom
GET {{baseURL}}/browser/{{session_id}}/dom

###

POST {{baseURL}}/browser/open

### 

POST {{baseURL}}/browser/7077cb4e-f8a2-4a0e-a76c-792c6e4b2b7c/navigate
Content-Type: application/json

{ "page_id" : 1 }

###

POST {{baseURL}}/browser/7077cb4e-f8a2-4a0e-a76c-792c6e4b2b7c/wait-for-page
Content-Type: application/json

{ "page_id" : 1, "timeout": 10 }

###

GET {{baseURL}}/browser/7077cb4e-f8a2-4a0e-a76c-792c6e4b2b7c/get-current-page

###

POST {{baseURL}}/browser/7077cb4e-f8a2-4a0e-a76c-792c6e4b2b7c/set-value
Content-Type: application/json

{ "page_id" : 1, "selector_alias": "input", "value": "easyautomate" }

###