@baseURL = http://localhost:8765



DELETE {{baseURL}}/api/applications/1

###

POST {{baseURL}}/api/applications
Content-Type: application/json

{
  "name": "Google"
}

###

POST {{baseURL}}/api/pages
Content-Type: application/json

{
  "name": "Google Search",
  "url": "https://www.google.com?hl=en&gl=US",
  "application_id": 1,
  "can_be_navigated_to": true,
  "identifying_selectors": [ { "alias": "input", "xpath": "//textarea[@maxlength=2048]" }, {"alias": "accept", "xpath": "//button//div[contains(text(), 'ccept')]", "visible": "False"} ],
  "interactive_selectors": [] 
}
###

###

POST {{baseURL}}/api/pages
Content-Type: application/json

{
  "name": "Google Search (Confirm Cookie)",
  "url": "https://www.google.com?hl=en&gl=US",
  "application_id": 1,
  "can_be_navigated_to": true,
  "identifying_selectors": [ { "alias": "input", "xpath": "//textarea[@maxlength=2048]" }, {"alias": "accept", "xpath": "//button//div[contains(text(), 'ccept')]", "visible": "True"} ],
  "interactive_selectors": [] 
}
###

GET {{baseURL}}/api/applications


### 
GET {{baseURL}}/api/pages

###

POST {{baseURL}}/api/pages
Content-Type: application/json

{
  "name": "Google Search Result",
  "url": "",
  "application_id": 1,
  "can_be_navigated_to": false,
  "identifying_selectors": { "searchfield": "//div[@id='searchform']" },
  "interactive_selectors": {}
}

###





###

# @name openSession
POST {{baseURL}}/api/browser/open
Content-Type: application/json

{}

###

# @session_id = {{openSession.response.body.session_id}}

# @name closeSession
POST {{baseURL}}/api/browser/{{session_id}}/close
Content-Type: application/json

@session_id = {{openSession.response.body.session_id}}
###

# @name navigateToPage

POST {{baseURL}}/api/browser/{{session_id}}/navigate
Content-Type: application/json

{
  "page_id": "1"
}

###


# @name clickElement
# @session_id = {{openSession.response.body.session_id}}

POST {{baseURL}}/api/browser/{{session_id}}/click
Content-Type: application/json

{
  "page_id": "2",
  "selector_alias": "accept"
}

###

# @name setElementValue
POST {{baseURL}}/api/browser/{{session_id}}/set-value
Content-Type: application/json

{
  "page_id": "1",
  "selector_alias": "input",
  "value": "selenium\n"
}

###

# @name getElementValue
POST {{baseURL}}/api/browser/{{session_id}}/get-value

Content-Type: application/json
{
  "page_id": "<PAGE_ID>",
  "selector_alias": "<SELECTOR_ALIAS>"
}

###

# @name waitForPage
POST {{baseURL}}/api/browser/{{session_id}}/wait-for-page

Content-Type: application/json
{
  "page_id": "<PAGE_ID>",
  "timeout": 10
}

###

# @name getCurrentPage
GET {{baseURL}}/api/browser/{{session_id}}/get-current-page

###

# @name checkSelectors
GET {{baseURL}}/api/browser/{{session_id}}/checkSelectors

###

# @name takeScreenshot
GET {{baseURL}}/api/browser/{{session_id}}/screenshot
Content-Type: application/json

###

# @name getDom
GET {{baseURL}}/api/browser/{{session_id}}/dom

###

POST {{baseURL}}/api/browser/open

### 

POST {{baseURL}}/api/browser/{{session_id}}/navigate
Content-Type: application/json

{ "page_id" : 1 }

###

POST {{baseURL}}/api/browser/{{session_id}}/wait-for-page
Content-Type: application/json

{ "page_id" : 1, "timeout": 10 }

###

GET {{baseURL}}/api/browser/{{session_id}}/get-current-page

###

POST {{baseURL}}/api/browser/{{session_id}}/set-value
Content-Type: application/json

{ "page_id" : 1, "selector_alias": "input", "value": "easyautomate" }

###